# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=511)),
                ('description', models.CharField(max_length=511)),
                ('date_start', models.DateTimeField(verbose_name='date_start')),
                ('date_finish', models.DateTimeField(verbose_name='date_finish')),
                ('site_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('coordinates', models.CharField(max_length=255)),
                ('site_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Organisation'),
        ),
    ]
