# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20171025_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='organisation',
        ),
        migrations.AddField(
            model_name='contest',
            name='coordinates',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contest',
            name='category',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Category_contest',
        ),
        migrations.DeleteModel(
            name='Organisation',
        ),
    ]
